### ISSUE TITLE
Apple Silicon request

### ISSUE THREAD

**Issue by HenkMutsaerts** [flathub/org.freedesktop.LinuxAudio.Plugins.Tunefish4#5]
Dear developers,

May I ask you if it is possible for you to recompile TuneFish4 for Apple's new Silicon architecture (MACA64/ARM64)?
I'm happy to help with this if you tell me which compilers/libraries etc I need to install!

Thanks, Henk (work as MRI image analysis & music as hobby)

**Comment by hfiguiere** [comment]
You should ask upstream to fix their code. It doesn't build on anything but x86_64. https://github.com/paynebc/tunefish

Also I assume that you are not asking for a macOS version, because that's definitely the wrong place.

**Comment by hfiguiere** [comment]
Just a quick note. I had forgotten that I had patched to build on aarch64 (still I shouldn't have to) but that is was disablre, and now that I have confirmed it works on my setup (a Raspberry Pi 400), I'll merge it.
